# Generated by Django 4.1.7 on 2023-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
