# Generated by Django 4.1.7 on 2023-03-03 17:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_person_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='CZ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=models.CharField(default='', max_length=12),
        ),
    ]
