# Generated by Django 4.1.7 on 2023-02-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_product_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='conclusion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
