# Generated by Django 4.1.7 on 2023-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='payment',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
