# Generated by Django 4.1.7 on 2023-03-16 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_alter_contract_payment_alter_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='conclusion_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum uzavření'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Pojištěnec'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment',
            field=models.PositiveIntegerField(verbose_name='Pravidelná platba'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance_app.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.CharField(default='', max_length=150, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Adresa - druhý řádek'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=150, verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Křestní jméno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Zaměstnanec'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Administrátor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='CZ', verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=models.CharField(default='', max_length=12, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Název'),
        ),
    ]
