# Generated by Django 4.1.7 on 2023-02-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_app', '0006_insurance_payment'),
    ]

    operations = [

        migrations.RenameModel(
            old_name='Insurance',
            new_name='Contract',
        ),
    ]
