# Generated by Django 4.1.7 on 2023-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0007_alter_contract_conclusion_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt'},
        ),
    ]
