# Generated by Django 4.1.7 on 2023-03-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Datum události')),
                ('description', models.TextField(verbose_name='Popis události')),
                ('approved', models.BooleanField(default=False, verbose_name='Schváleno')),
                ('payout', models.IntegerField(null=True, verbose_name='Pojistné plnění')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract', verbose_name='Smlouva')),
            ],
        ),
    ]
