# Generated by Django 4.1.7 on 2023-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_insuredevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredevent',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Zpracováno'),
        ),
    ]
