# Generated by Django 4.1.7 on 2023-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_insuredevent_reporting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredevent',
            name='payout',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pojistné plnění'),
        ),
    ]
