# Generated by Django 4.1.7 on 2023-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0012_alter_insuredevent_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='conclusion_date',
            field=models.DateField(auto_now_add=True, verbose_name='Datum uzavření'),
        ),
    ]
