# Generated by Django 4.1.6 on 2023-02-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('house_number', models.IntegerField(blank=True, null=True)),
                ('building_id_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('conclusion_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('annual_price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(db_index=True, max_length=256, unique=True)),
                ('id_domicile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='domicile', to='insurance_app.address')),
                ('id_mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mailing_address', to='insurance_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Insured_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('approved', models.BooleanField(default=False)),
                ('payout', models.IntegerField(default=0)),
                ('id_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurance')),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='id_insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insured', to='insurance_app.user'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='id_policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policyholder', to='insurance_app.user'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance_app.products'),
        ),
    ]
